name: example
description: Demo for the voice_chat_input package.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.4.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  voice_chat_input:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
